service:
  port: 8095

catalogs:
  nessie: |
    connector.name=iceberg
    fs.native-gcs.enabled=true
    gcs.json-key-file-path=/etc/creds/gcp_creds.json
    iceberg.catalog.type=nessie
    iceberg.nessie-catalog.uri=${nessie_uri}
    iceberg.nessie-catalog.ref=main
    iceberg.nessie-catalog.default-warehouse-dir=${warehouse_dir}
    iceberg.register-table-procedure.enabled=true

env:
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: /etc/creds/gcp_creds.json

secretMounts:
  - name: gcp-creds
    secretName: gcp-creds
    path: /etc/creds