cp-zookeeper:
  enabled: false

cp-kafka:
  enabled: false

cp-ksql-server:
  enabled: false

cp-control-center:
  enabled: false

cp-schema-registry:
  kafka:
    bootstrapServers: "PLAINTEXT://${kafka_service_name}.${namespace}:9092"
  prometheus:
    jmx:
      enabled: false
  resources:
    limits:
      ephemeral-storage: "1Gi"

cp-kafka-rest:
  cp-kafka:
    bootstrapServers: "PLAINTEXT://${kafka_service_name}.${namespace}:9092"
  prometheus:
    jmx:
      enabled: false
  resources:
    limits:
      ephemeral-storage: "1Gi"

cp-kafka-connect:
  enabled: false