FROM apache/beam_python3.10_sdk:2.61.0

ARG BEAM_VERSION
ENV BEAM_VERSION=${BEAM_VERSION:-2.61.0}
ENV REPO_BASE_BEAM_URL=https://repo1.maven.org/maven2/org/apache/beam

RUN apt-get update && apt-get install -y default-jdk

RUN mkdir -p /opt/apache/beam/jars \
  && wget ${REPO_BASE_BEAM_URL}/beam-sdks-java-io-expansion-service/${BEAM_VERSION}/beam-sdks-java-io-expansion-service-${BEAM_VERSION}.jar \
          --progress=bar:force:noscroll -O /opt/apache/beam/jars/beam-sdks-java-io-expansion-service.jar

RUN wget ${REPO_BASE_BEAM_URL}/beam-sdks-java-io-hadoop-common/${BEAM_VERSION}/beam-sdks-java-io-hadoop-common-${BEAM_VERSION}.jar \
    --progress=bar:force:noscroll -O /opt/apache/beam/jars/beam-sdks-java-io-hadoop-common.jar
RUN wget ${REPO_BASE_BEAM_URL}/beam-sdks-java-io-iceberg/${BEAM_VERSION}/beam-sdks-java-io-iceberg-${BEAM_VERSION}.jar \
    --progress=bar:force:noscroll -O /opt/apache/beam/jars/beam-sdks-java-io-iceberg.jar

RUN mkdir -p /test_from_kafka_to_iceberg_write/test/write_read
RUN chmod -R 777 /test_from_kafka_to_iceberg_write

COPY beam_app /app/beam_app

RUN pip install -e /app/beam_app/.

ENV PYTHONPATH="$PYTHONPATH:/app"